 <!--about-->
    <section id="section-about">
      <div class="container">
        <div class="about">
          <div class="row mar-bot40">
            <div class="col-md-offset-3 col-md-6">
              <div class="title">
                <div class="wow bounceIn">
                  <h2 class="section-heading animated" data-animation="bounceInUp">Nosotros</h2>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="row-slider">
              <div class="col-lg-6 mar-bot30">
                <div class="responsive-slider" data-spy="responsive-slider" data-autoplay="true">
                  <div class="slides" data-group="slides">
                    <ul>
                      <div class="slide-body" data-group="slide">
                        <li><img alt="" class="img-responsive" src="<?php echo $_layoutParams["ruta_img"]; ?>9.jpg" width="100%" height="350"/></li>
                        <li><img alt="" class="img-responsive" src="<?php echo $_layoutParams["ruta_img"]; ?>10.jpg" width="100%" height="350"/></li>
                        <li><img alt="" class="img-responsive" src="<?php echo $_layoutParams["ruta_img"]; ?>11.jpg" width="100%" height="350"/></li>
                      </div>
                    </ul>
                    <a class="slider-control left" href="#" data-jump="prev"><i class="fa fa-angle-left fa-2x"></i></a>
										<a class="slider-control right" href="#" data-jump="next"><i class="fa fa-angle-right fa-2x"></i></a>
                  </div>
                </div>
              </div>
              <div class="col-lg-6 ">
                <div class="company mar-left10">
                  <h4>La finalida de esta  pagina es ofrecer servicios  y adquirirlos <span>Calificando y recomendando los mismos</span>asegurando con esto la garantia  y  el compromiso de los prestadores de esta</h4>
                  <p>el  registro es totalmente  gratuito con el  fin  de  encaminar todos los servicios  informales</p>
                </div>
                <div class="list-style">
                  <div class="row">
                    <div class="col-lg-6 col-sm-6 col-xs-12">
                      <ul>
                        <li>Albañileria</li>
                        <li>Plomeria</li>
                        <li>Carpinteria</li>
                        <li>Telefonia movil (Celulares)</li>
                      </ul>
                    </div>
                    <div class="col-lg-6 col-sm-6 col-xs-12">
                      <ul>
                        <li>Mantenimiento</li>
                        <li>Tecnicos en computo</li>
                        <li>desarollo web</li>
                        <li>Electricistass</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    

	