
		<!-- Header -->


			<header id="header">

				<a href="" class="image avatar"><img src="<?php echo $_layoutParams["ruta_img"]; ?>avatar.jpg" alt="" /></a>
				<h1><strong><?php echo  $_SESSION['username'];?></strong>, dedicado a la administracios<br />
				amigable y  con buena  actitud<br />
				 <a href="index">Inicio</a>.</h1>
			</header>

		<!-- Main -->
			<div id="main">

				<!-- One -->
					<section id="one">
						<header class="major">
							<h2>Un poco  sobre mi </h2>
						</header>
						<p>Mi actitud laboral es .--------------------------
							y con esto n yo me concidero el mas apto en el area de __________---</p>
						<ul class="actions">
							<li><a href="#" class="button">Learn More</a></li>
						</ul>
					</section>

				<!-- Two -->
					<section id="two">
						<h2>Trabajos elaborados </h2>
						<div class="row">
							<article class="6u 12u$(xsmall) work-item">
								<a href="../img/fulls/01.jpg" class="image fit thumb"><img src="../img/thumbs/01.jpg" alt="" /></a>
								<h3>-------------</h3>
								<p>---------------.</p>
							</article>
							<article class="6u$ 12u$(xsmall) work-item">
								<a href="../img/fulls/02.jpg" class="image fit thumb"><img src="../img/thumbs/02.jpg" alt="" /></a>
								<h3>>-------------</</h3>
								<p>>-------------</</p>
							</article>
							<article class="6u 12u$(xsmall) work-item">
								<a href="../img/fulls/03.jpg" class="image fit thumb"><img src="../img/thumbs/03.jpg" alt="" /></a>
								<h3>Tortor metus commodo</h3>
								<p>>-------------</ñ</p>
							</article>
							<article class="6u$ 12u$(xsmall) work-item">
								<a href="../img/fulls/04.jpg" class="image fit thumb"><img src="../img/thumbs/04.jpg" alt="" /></a>
								<h3>>-------------</</h3>
								<p>>-------------</.</p>
							</article>
							<article class="6u 12u$(xsmall) work-item">
								<a href="../img/fulls/05.jpg" class="image fit thumb"><img src="../img/thumbs/05.jpg" alt="" /></a>
								<h3>>-------------</</h3>
								<p>>-------------</</p>
							</article>
							<article class="6u$ 12u$(xsmall) work-item">
								<a href="../img/fulls/06.jpg" class="image fit thumb"><img src="../img/thumbs/06.jpg" alt="" /></a>
								<h3>>-------------</</h3>
								<p>>-------------</</p>
							</article>
						</div>
						<ul class="actions">
							<li><a href="#" class="button">Mostrar todos los trabajos</a></li>
						</ul>
					</section>

				<!-- Three -->
					<section id="three">
						<h2>Preguntas</h2>
						<p>></p>
						<div class="row">
							<div class="8u 12u$(small)">
								<form method="post" action="#">
									<div class="row uniform 50%">
										<div class="6u 12u$(xsmall)"><input type="text" name="name" id="name" placeholder="Name" /></div>
										<div class="6u$ 12u$(xsmall)"><input type="email" name="email" id="email" placeholder="Email" /></div>
										<div class="12u$"><textarea name="message" id="message" placeholder="Message" rows="4"></textarea></div>
									</div>
								</form>
								<ul class="actions">
									<li><input type="submit" value="Send Message" /></li>
								</ul>
							</div>
							<div class="4u$ 12u$(small)">
								<ul class="labeled-icons">
									<li>
										<h3 class="icon fa-home"><span class="label">Direccion</span></h3>
										conocido.<br />
										TN 00000<br />
										Playa del carmen
									</li>
									<li>
										<h3 class="icon fa-mobile"><span class="label">Telefono</span></h3>
										000-000-0000
									</li>
									<li>
										<h3 class="icon fa-envelope-o"><span class="label">Correo </span></h3>
										<a href="#">hello@abner.tld</a>
									</li>
								</ul>
							</div>
						</div>
					</section>