<!-- services -->
    <section id="services" class="section pad-bot5 bg-white">
		<div class="container">
				<div class="row mar-bot5">
					<div class="col-md-offset-3 col-md-6">
						<div class="section-header">
						<div class="wow bounceIn"data-animation-delay="7.8s">

							<h2 class="section-heading animated"  >Mercado de servicios libre</h2>

							<h4>Donde  encontrar un servicio y ofrecerlo es facíl solo con 3 sencillos pasos</h4>

						</div>
						</div>
					</div>
				</div>
			<div class="row mar-bot40">
				<div class="col-lg-4" >
					<div class="wow bounceIn">
						<div class="align-center">

							<div class="wow rotateIn">
								<div class="service-col">
									<div class="service-icon">
										<figure><i class="fa fa-cog"></i></figure>
									</div>
										<h2><a href="login.html">Registrate</a></h2>
										<p>Registrate  y configura tu cuenta Para poder solicitar u ofrecer un servicio y asegurarte como
											cliente o servidor  tienes que  registrarte  y configurar tus datos

										</p>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="col-lg-4" >
					<div class="align-center">
						<div class="wow bounceIn">

							<div class="wow rotateIn">
								<div class="service-col">
									<div class="service-icon">
										<figure><i class="fa fa-desktop"></i></figure>
									</div>
										<h2><a href="#">Consulta</a></h2>
										<p>Consulta los  servicios  u oferta uno</p>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="col-lg-4" >
					<div class="align-center">
						<div class="wow bounceIn">
							<div class="service-col">
								<div class="service-icon">
									<figure><i class="fa fa-dropbox"></i></figure>
								</div>
									<h2><a href="#">Califica</a></h2>
									<p>Con tu calificacion podras  apoyar   a la comunidad  recomendado o  apoyando con criticas constructivas
										hacia los clientes o  servidores
									</p>
							</div>
						</div>
					</div>
				</div>

			</div>

		</div>
	</section>