
<!--<h2>Inicio de sesion</h2>
<form action="<?php ?>" method="POST" accept-charset="utf-8">
		<p>Username <input type="text" name="username" ></p>
	<p>Password<input type="password" name="password" ></p>
	<button type= "submit">Iniciar</button>
</form>
-->

	<section id="section-contact" class="section appear clearfix">
			<div class="container">

				<div class="row mar-bot40">
					<div class="col-md-offset-3 col-md-6">
						<div class="section-header">
							<h2 class="section-heading animated" data-animation="bounceInUp">Inicia sesion</h2>
							<p>Al iniciar  secion podras contribuir  a los comentarios de los profesionistas  y mejorar la calidad del servicios</p>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<div class="cform" id="contact-form">
							<div id="sendmessage">
								 Tu mensaje  ha sido enviado con exito!
							</div>
							<form action="<?php echo APP_URL.'usuarios/login'; ?>" method="POST"  accept-charset="utf-8"role="form" >
							<div class="wow bounceIn">
							  <div class="form-group">
								<label for="name">Nombre se usuarios</label>
								<input type="text" name="username" class="form-control" id="username" placeholder="Tu nombre de  usuario" data-rule="maxlen:4" data-msg="Please enter at least 4 chars" />
								<div class="validation"></div>
							  </div>
							  <div class="wow bounceIn">
							  <div class="form-group">
								<label for="name">Contraseña</label>
								<input type="password" name="password" class="form-control" id="password" placeholder="Tu nombre de  usuario" data-rule="maxlen:4" data-msg="Favor de  ingresar mas de 4 caracteres" />
								<div class="validation"></div>
							  </div>
							  <button type="submit" class="line-btn green">iniciar sesion</button>

							</form>
							 

						</div>
					</div>
					<!-- ./span12 -->
				</div>
			</section>
