  <!--m action="" method="POST">
	<p>Email <input type="email" name="email"></p>
	<p>Username <input type="text" name="username"></p>
	<p>Password <input type="password" name="password"></p>
	<p>Status <input type="number" name="status"></p>
	<p><input type="submit"></p>
</form>
-->
	<section id="section-contact" class="section appear clearfix">
			<div class="container">

				<div class="row mar-bot40">
					<div class="col-md-offset-3 col-md-6">
						<div class="section-header">
							<h2 class="section-heading animated" data-animation="bounceInUp">Resgitrate</h2>
							<p>Enviaremos  un mensaje despues de haber registrado para validar la aplicacion</p>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<div class="cform" id="contact-form">
							<div id="sendmessage">
								 Tu mensaje  ha sido enviado con exito!
							</div>
							<form action="<?php echo APP_URL.'usuarios/add'; ?>" method="post" role="form" class="contactForm">
							<div class="wow bounceIn">
							  <div class="form-group">
								<label for="name">Nombre se usuarios</label>
								<input type="text" name="username" class="form-control" id="username" placeholder="Tu nombre de  usuario" data-rule="maxlen:4" data-msg="Please enter at least 4 chars" />
								<div class="validation"></div>
							  </div>
							  <div class="wow bounceIn">
							  <div class="form-group">
								<label for="name">Contraseña</label>
								<input type="password" name="password" class="form-control" id="password" placeholder="Tu nombre de  usuario" data-rule="maxlen:4" data-msg="Favor de  ingresar mas de 4 caracteres" />
								<div class="validation"></div>
							  </div>
							  <div class="form-group">
								<label for="email">Tu correo</label>
								<input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
								<div class="validation"></div>
							  </div>
							  <div class="form-group">
								<label for="edad">Edad</label>
								<input type="text" class="form-control" name="edad" id="subject" placeholder="Edad" data-rule="maxlen:4" data-msg="Please enter at least 8 chars of subject" />
								<div class="validation"></div>
							  </div>
							  <div class="form-group">
								<label for="message">Describete</label>
								<textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us"></textarea>
								<div class="validation"></div>
							  </div>
							</div>
							  <button type="submit" class="line-btn green">Registrar</button>
							</form>

						</div>
					</div>
					<!-- ./span12 -->
				</div>

			</div>
		</section>