
   
  <section class="featured">
    <div id="index">
      <!-- Responsive slider - START -->
      <div class="responsive-slider" data-spy="responsive-slider" data-autoplay="true">
        <div class="slides" data-group="slides">
          <ul>
            <li>
              <div class="slide-body" data-group="slide">
                <img src="<?php echo $_layoutParams["ruta_img"]; ?>8.jpg" alt="">
                <div class="caption header" data-animate="slideAppearUpToDown" data-delay="500" data-length="300">
                  <h2></h2>
                  <div class="caption-sub" data-animate="slideAppearDownToUp" data-delay="1200" data-length="300"><h4><span></span></h4></div>
                  <div class="caption-sub" data-animate="slideAppearLeftToRight" data-delay="800" data-length="300"><h3></h3></div>
                </div>
              </div>
            </li>
            <li>
              <div class="slide-body" data-group="slide">
                <img src="<?php echo $_layoutParams["ruta_img"]; ?>2.jpg" alt="">
                <div class="caption header" data-animate="slideAppearDownToUp" data-delay="500" data-length="300">
                  <h2>Oferta  y demanda  tus servicios</h2>
                  <div class="caption-sub" data-animate="slideAppearUpToDown" data-delay="800" data-length="300"><h4>
                    <span>	si  requieres  buscas  o necesitas de algun trabajo  estas  en el lugar ideal</span>
                  </h4>
                </div>
                <div class="caption-sub" data-animate="slideAppearRightToLeft" data-delay="1200" data-length="300"><h3>
                  La major manera de  contactar y calificar </h3>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="slide-body" data-group="slide">
              <img src="<?php echo $_layoutParams["ruta_img"]; ?>6.jpg" alt="">
              <div class="caption header" data-animate="slideAppearUpToDown" data-delay="500" data-length="300">
                <h2>Crea un perfil lider </h2>
                <div class="caption-sub" data-animate="slideAppearLeftToRight" data-delay="800" data-length="300">
                  <h4>busca adquiere califica</h4></div>
                  <div class="caption-sub" data-animate="slideAppearDownToUp" data-delay="1200" data-length="300">
                    <h3><span>Registrate</span></h3></div>
                  </div>
                </div>
              </li>
            </ul>
          </div>
          <a class="slider-control left" href="#" data-jump="prev"><i class="fa fa-angle-left fa-2x"></i></a>
          <a class="slider-control right" href="#" data-jump="next"><i class="fa fa-angle-right fa-2x"></i></a>
        </div>
        <!-- Responsive slider - END -->
      </div>
    </section>
   